export const initialBreedInfo = {
    weight: {
      imperial: "",
      metric: "",
    },
    id: "",
    name: "",
    cfa_url: "",
    vetstreet_url: "",
    vcahospitals_url: "",
    temperament: "",
    origin: "",
    country_codes: "",
    country_code: "",
    description: "",
    life_span: "",
    indoor: 0,
    lap: 0,
    alt_names: "",
    adaptability: 0,
    affection_level: 0,
    child_friendly: 0,
    dog_friendly: 0,
    energy_level: 0,
    grooming: 0,
    health_issues: 0,
    intelligence: 0,
    shedding_level: 0,
    social_needs: 0,
    stranger_friendly: 0,
    vocalisation: 0,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: "",
    hypoallergenic: 0,
    reference_image_id: ""
}

export const paths = {
    GET_CURRENT_BREED_IMAGE: "https://api.thecatapi.com/v1/images/search?api_key=live_bqQzOlFgfMy3RUxp4XNIc68N18npchoJGyfkYQQDRuFp3Lm2Wx6YbV82xWf3gZkW&breed_ids=",
    GET_ALL_BREEDS: "https://api.thecatapi.com/v1/breeds",
}